# Generated by Django 3.1.1 on 2020-09-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regLogin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
