# Generated by Django 3.1.1 on 2020-09-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0005_auto_20200908_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='dojo_location',
        ),
    ]
